### ISSUE TITLE
GUI fails when training acoustic model

### ISSUE THREAD

**Issue by rhagarty** [IBM/Train-Custom-Speech-Model#28]
status in GUI reads: "training", but see the following errors in the console:

```bash
00/train Chrome 71.0 Mac OS X 10.14.0 538.350548 ms (req_id=01eeef73-f715-4bc3-b007-c44a34baec8f, remote-address=::ffff:127.0.0.1, ip=::ffff:127.0.0.1, method=GET, url=/api/acoustic-model, referer=http://localhost:3000/train, body={}, short-body={}, http-version=1.1, response-time=538.350548, status-code=200, incoming=<--)
[0] [2019-02-26T22:26:16.412Z]  INFO: logger/43680 on Richs-MBP-15.attlocal.net: ::ffff:127.0.0.1 <-- GET /api/acoustic-model HTTP/1.1 200 369 http://localhost:3000/train Chrome 71.0 Mac OS X 10.14.0 566.323107 ms (req_id=7cbc3d9e-4b51-441b-bf93-6dbb7cecbe30, remote-address=::ffff:127.0.0.1, ip=::ffff:127.0.0.1, method=GET, url=/api/acoustic-model, referer=http://localhost:3000/train, body={}, short-body={}, http-version=1.1, response-time=566.323107, status-code=200, incoming=<--)
[0] (node:43680) UnhandledPromiseRejectionWarning: RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ETIMEDOUT
[0]     at ServerResponse.writeHead (_http_server.js:208:11)
[0]     at ServerResponse.writeHead (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/on-headers/index.js:55:19)
[0]     at ServerResponse.writeHead (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/on-headers/index.js:55:19)
[0]     at ServerResponse._implicitHeader (_http_server.js:199:8)
[0]     at ServerResponse.write (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/compression/index.js:84:14)
[0]     at writetop (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express-session/index.js:290:26)
[0]     at ServerResponse.end (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express-session/index.js:338:16)
[0]     at ServerResponse.send (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express/lib/response.js:221:10)
[0]     at ServerResponse.json (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express/lib/response.js:267:15)
[0]     at /Users/rhagarty/journeys/Train-Custom-Speech-Model/dist/controllers/api.js:123:70
[0] (node:43680) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[0] (node:43680) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[0] _http_server.js:208
[0]     throw new ERR_HTTP_INVALID_STATUS_CODE(originalStatusCode);
[0]     ^
[0]
[0] RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: ETIMEDOUT
[0]     at ServerResponse.writeHead (_http_server.js:208:11)
[0]     at ServerResponse.writeHead (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/on-headers/index.js:55:19)
[0]     at ServerResponse.writeHead (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/on-headers/index.js:55:19)
[0]     at ServerResponse._implicitHeader (_http_server.js:199:8)
[0]     at ServerResponse.end (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/compression/index.js:103:14)
[0]     at writeend (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express-session/index.js:261:22)
[0]     at Immediate.onsave (/Users/rhagarty/journeys/Train-Custom-Speech-Model/node_modules/express-session/index.js:335:11)
[0]     at processImmediate (timers.js:632:19)
[1] Proxy error: Could not proxy request /api/acoustic-model from localhost:3000 to http://localhost:5000/.
[1] See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNRESET).
```

If I run `list_acoustic_model.py`, I get the following:
```bash
Getting custom acoustic models...
Get acoustice models returns:  200
{"customizations": [
   {
      "owner": "4493493e-2a2a-4eb1-8845-a915035a4142",
      "base_model_name": "en-US_NarrowbandModel",
      "customization_id": "43bc9966-fe48-4f9b-8d88-405091e4c5a9",
      "versions": ["en-US_NarrowbandModel.v2018-07-31"],
      "created": "2019-02-25T23:09:02.767Z",
      "name": "Acoustic model 1",
      "description": "My narrowband acoustic model",
      "progress": 0,
      "language": "en-US",
      "status": "ready"
   },
   {
      "owner": "4493493e-2a2a-4eb1-8845-a915035a4142",
      "base_model_name": "en-US_NarrowbandModel",
      "customization_id": "edb9a7ce-082c-42b3-8289-a8f4fa5eeffb",
      "versions": ["en-US_NarrowbandModel.v2018-07-31"],
      "created": "2019-02-25T23:37:32.070Z",
      "name": "Acoustic-model-1",
      "description": "Custom acoustic model for user1",
      "progress": 0,
      "language": "en-US",
      "status": "training"
   }
]}
```

**Comment by tonanhngo** [comment]
@yhwang @pvaneck Does this look like something in the GUI code that's not happy about the response from Watson?  The training seems to take off and run fine.

**Comment by rhagarty** [comment]
resolved
